### ISSUE TITLE
사용자 및 Spring Security에 대한 기능을 구현한다.

### ISSUE THREAD

**Issue by LeeA0** [Dog-Han-Developer/doggu_v1.0#3]
## 목적
덕구 사용자 정보의 보안을 위해 관련 기능을 구현한다.

## 작업 상세 내용

- [x]  SecurityConfig와 이에 필요한 요소들을 구현한다.
- [x]  User 도메인을 구현한다.

**Comment by callipenguin** [comment]
세팅하느라 고생 많으셨습니다.. 감사합니다!!
